### ISSUE TITLE
Adjustment POAP Allocation Factors

### ISSUE THREAD

**Issue by annamsgeorge** [gnosis/cow-token-allocation#1]
Based on community feedback we are slightly adjusting factors used for the POAP allocations.

Changes include:
- reducing "Kaffee 24/9" by 50%. This is effectively done by multiplying all other categories *2. 
- reducing the allocation for "SC Deployment 24h Special Mainnet" to factor 2. 

Overview new factors:

> <google-sheets-html-origin><style type="text/css"></style>

Factor | Event | Token ID
-- | -- | --
4 | Kaffee 23/7 | 4437
4 | Kaffee 30/7 | 4813
4 | Kaffee 6/8 | 5182
2 | SC Deployment 24h Special Mainnet | 6102
2 | SC Deployment 24h Special xDai | 6103
4 | Kaffee 27/8 | 6457
100 | CowStar August | 6739
4 | Kaffee 3/9 | 6887
2 | Kaffee 10/9 | 7330
2 | Kaffee 17/9 | 8092
1 | Kaffee 24/9 | 8824
100 | CowStar September | 9533
40 | UX Participants | 11743
100 | Picasso Winner | 12420
100 | CowStar October | 12654
20 | Coffee Challenge Winner 5/11 | 13346
20 | Coffee Challenge Winner 19/11 | 15296
20 | Squid | 15311
20 | Coffee Challenge Winner 26/11 | 15739
100 | CowStar November | 18465
20 | Coffee Challenge Winner 17/12 | 21839
100 | CowStar December | 22201
16 | Alpha Mainnet | [Dune query]
4 | Alpha Gchain | [Dune query]

**Comment by bh2smith** [comment]
Sorry forgot to update alpha traders. Just a moment.
